uploads = []
generated = []

[[outputs]]
id = "74CDwR9nQSOqC0tE0Zw53"
uri = "file://onukonu-pet-boarding-core.zip"
type = "unspecified"
title = "onukonu-pet-boarding-core.zip — Fully Patched Production Plugin"

[[outputs]]
id = "wxjt0FYgGe1hv6FcN0SL2"
uri = "file://onukonu-pet-boarding-core-v1.0.1.zip"
type = "unspecified"
title = "onukonu-pet-boarding-core-v1.0.1.zip"
