uploads = []
generated = []

[[outputs]]
id = "74CDwR9nQSOqC0tE0Zw53"
uri = "file://onukonu-pet-boarding-core.zip"
type = "unspecified"
title = "onukonu-pet-boarding-core.zip — Fully Patched Production Plugin"

[[outputs]]
id = "wxjt0FYgGe1hv6FcN0SL2"
uri = "file://onukonu-pet-boarding-core-v1.0.1.zip"
type = "unspecified"
title = "onukonu-pet-boarding-core-v1.0.1.zip"

[[outputs]]
id = "PMz9ASOY6HR3i3hiTde6g"
uri = "file://onukonu-pet-boarding-core-v1.0.2.zip"
type = "unspecified"
title = "onukonu-pet-boarding-core-v1.0.2.zip"

[[outputs]]
id = "ix_A7qqG1cyQGQUfjj_R3"
uri = "file://onukonu-pet-boarding-core-v1.0.3.zip"
type = "unspecified"
title = "onukonu-pet-boarding-core-v1.0.3.zip"

[[outputs]]
id = "MdcDPmkfcVrhxbWPwK7-d"
uri = "file://onukonu-pet-boarding-core-v1.0.4.zip"
type = "unspecified"
title = "onukonu-pet-boarding-core-v1.0.4.zip — Deployment candidate"

[[outputs]]
id = "Z8Mm9WHX9DuH3JdmatP9P"
uri = "file://onukonu-pet-boarding-core-v1.0.5.zip"
type = "unspecified"
title = "onukonu-pet-boarding-core-v1.0.5.zip — Import diagnostics"

[[outputs]]
id = "_HJ_NZzF2zb_8heYohpxu"
uri = "file://onukonu-pet-boarding-core-v1.0.6.zip"
type = "unspecified"
title = "onukonu-pet-boarding-core-v1.0.6.zip — Branch resolution fix"

[[outputs]]
id = "KqlGDexVnfKKGkFrQbcQ4"
uri = "file://onukonu-pet-boarding-core-v1.0.7.zip"
type = "unspecified"
title = "onukonu-pet-boarding-core-v1.0.7.zip — BranchResolver service"
